name: Build & Publish

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Check commit message
        id: commit_check
        run: |
          if git log -1 --pretty=%B | grep -q "\[skip-central\]"; then
            echo "skip_central=true" >> $GITHUB_OUTPUT
          else
            echo "skip_central=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew buildAndCollect

      - name: Publish to Maven Central
        if: steps.commit_check.outputs.skip_central == 'false'
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Platform
        run: ./gradlew publishMods
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          files: "build/libs/*/topper*.jar"